version: "3.7"
services:
    app:
        build:
            context: .
            dockerfile: workers/Dockerfile
        volumes:
            - ./workers:/usr/src/workers
        restart: "no"
        environment:
            service_mode : prod
        depends_on:
            - redis

    redis:
        image: redis:6-alpine
        restart: always
        ports:
            - "6379:6379"
        expose:
            - "6379"

    workers:
        image: workers
        build:
            context: .
            dockerfile: workers/Dockerfile
        command: bash -c "supervisord -c /usr/src/workers/supervisord.conf -n"
        volumes:
            - ./workers:/usr/src/workers
        links:
            - redis
        depends_on:
            - redis
    rq-dashboard:
        image: rq-dashboard
        build:
            context: .
            dockerfile: rq-dashboard/Dockerfile
        ports:
            - '9181:9181'
        expose:
            - "9181"
        links:
            - redis
        depends_on:
            - redis
